/**
 * Transforms Playwright `codegen` output (a `@playwright/test` `test(...)`
 * block) into a SELF-CONTAINED, runnable ESM script compatible with
 * `worker/executor.ts`.
 *
 * The executor spawns `node script.mjs`, so the script must:
 *  - import from the `playwright` package (NOT `@playwright/test`)
 *  - launch a browser itself
 *  - read the base URL from PLAYWRIGHT_TARGET_URL ?? TARGET_URL
 *  - exit non-zero on failure (so the executor records "failed")
 */

/**
 * Extracts the statements inside the codegen `test('...', async ({ page }) => {
 * ... })` body. Falls back to using the whole input if no test block is found
 * (e.g. already-bare statements).
 */
function extractBody(code: string): string {
  // Find the async arrow callback body of test(...) / test.only(...).
  const start = code.search(/async\s*\(\s*\{[^}]*\}\s*\)\s*=>\s*\{/);
  if (start === -1) {
    // No test wrapper: strip imports and return the remaining statements.
    return code
      .split("\n")
      .filter((l) => !/^\s*import\b/.test(l) && !/^\s*const\s+\{/.test(l))
      .join("\n")
      .trim();
  }

  // Find the `=>` after the param list, then the body's opening brace.
  const arrowIdx = code.indexOf("=>", start);
  const braceStart = code.indexOf("{", arrowIdx);
  let depth = 0;
  let end = -1;
  for (let i = braceStart; i < code.length; i++) {
    const ch = code[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) return code.trim();
  return code.slice(braceStart + 1, end).trim();
}

/**
 * If a navigation uses the codegen start URL, rewrite it to honor the runtime
 * TARGET_URL. We replace `page.goto('<absolute>')` with `page.goto(baseUrl)`
 * for the FIRST goto, and keep relative gotos resolved against baseUrl.
 */
function rewriteGotos(body: string): string {
  let first = true;
  return body.replace(
    /page\.goto\(\s*(['"`])([^'"`]*)\1\s*\)/g,
    (_m, _q, url: string) => {
      if (first) {
        first = false;
        return "page.goto(baseUrl)";
      }
      // Subsequent navigations: resolve relative paths against baseUrl.
      if (/^https?:\/\//i.test(url)) {
        return `page.goto(${JSON.stringify(url)})`;
      }
      return `page.goto(new URL(${JSON.stringify(url)}, baseUrl).toString())`;
    },
  );
}

export function toRunnableScript(codegenOutput: string): string {
  const body = rewriteGotos(extractBody(codegenOutput));

  // Indent the body for readability inside the IIFE.
  const indented = body
    .split("\n")
    .map((l) => (l.trim() ? "    " + l : l))
    .join("\n");

  return `// Auto-generated by the QA Copilot Suite test recorder.
// Self-contained Playwright script (ESM) — runnable via \`node script.mjs\`.
import { chromium } from 'playwright';

const baseUrl =
  process.env.PLAYWRIGHT_TARGET_URL ?? process.env.TARGET_URL ?? 'about:blank';

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  try {
${indented}
    console.log('Recording playback completed successfully.');
  } catch (err) {
    console.error('Recording playback failed:', err);
    process.exitCode = 1;
  } finally {
    await context.close();
    await browser.close();
  }
})();
`;
}
